
title: Yukio Bergholdt - CMS Expert
url: 'https://yukio.dk'
baseurl: 'https://yukiob.github.io/online-cv/' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Yukio Bergholdt
tagline: CMS Expert / Frontend designer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: kontakt@yukio.dk
phone: +45 29729228
website: yukio.dk #do not add http://
linkedin: yukiob
#github: yukiob

#Update all the sections by editing the files inside _includes folder.
