
title: My Resume
url: 'http://yukio.dk'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Yukio Bergholdt
tagline: CMS Ekspert / Front end designer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: bergholdt@yukio.dk
#phone: 012 345 6789
website: yukio.dk #do not add http://
linkedin: alandoe
github: sharu725

#Update all the sections by editing the files inside _includes folder.
